#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6FormsApplication
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EET321_Lab6_S16")]
	public partial class EET321_Lab6DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEET321_Lab6_Table(EET321_Lab6_Table instance);
    partial void UpdateEET321_Lab6_Table(EET321_Lab6_Table instance);
    partial void DeleteEET321_Lab6_Table(EET321_Lab6_Table instance);
    #endregion
		
		public EET321_Lab6DataContext() : 
				base(global::Lab6FormsApplication.Properties.Settings.Default.EET321_Lab6_S16ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EET321_Lab6DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EET321_Lab6DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EET321_Lab6DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EET321_Lab6DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EET321_Lab6_Table> EET321_Lab6_Tables
		{
			get
			{
				return this.GetTable<EET321_Lab6_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EET321_Lab6_Table")]
	public partial class EET321_Lab6_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _DateTime;
		
		private char _GroupID;
		
		private string _BoardID;
		
		private float _Resistance;
		
		private float _OnTime;
		
		private System.Nullable<float> _Capacitance;
		
		private System.Nullable<float> _MeasMinOnTime;
		
		private System.Nullable<float> _MeasMaxOnTime;
		
		private System.Nullable<float> _MeasMinResistance;
		
		private System.Nullable<float> _MeasMaxResistance;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnGroupIDChanging(char value);
    partial void OnGroupIDChanged();
    partial void OnBoardIDChanging(string value);
    partial void OnBoardIDChanged();
    partial void OnResistanceChanging(float value);
    partial void OnResistanceChanged();
    partial void OnOnTimeChanging(float value);
    partial void OnOnTimeChanged();
    partial void OnCapacitanceChanging(System.Nullable<float> value);
    partial void OnCapacitanceChanged();
    partial void OnMeasMinOnTimeChanging(System.Nullable<float> value);
    partial void OnMeasMinOnTimeChanged();
    partial void OnMeasMaxOnTimeChanging(System.Nullable<float> value);
    partial void OnMeasMaxOnTimeChanged();
    partial void OnMeasMinResistanceChanging(System.Nullable<float> value);
    partial void OnMeasMinResistanceChanged();
    partial void OnMeasMaxResistanceChanging(System.Nullable<float> value);
    partial void OnMeasMaxResistanceChanged();
    #endregion
		
		public EET321_Lab6_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="NChar(1) NOT NULL", IsPrimaryKey=true)]
		public char GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoardID", DbType="NChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BoardID
		{
			get
			{
				return this._BoardID;
			}
			set
			{
				if ((this._BoardID != value))
				{
					this.OnBoardIDChanging(value);
					this.SendPropertyChanging();
					this._BoardID = value;
					this.SendPropertyChanged("BoardID");
					this.OnBoardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance", DbType="Real NOT NULL")]
		public float Resistance
		{
			get
			{
				return this._Resistance;
			}
			set
			{
				if ((this._Resistance != value))
				{
					this.OnResistanceChanging(value);
					this.SendPropertyChanging();
					this._Resistance = value;
					this.SendPropertyChanged("Resistance");
					this.OnResistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnTime", DbType="Real NOT NULL")]
		public float OnTime
		{
			get
			{
				return this._OnTime;
			}
			set
			{
				if ((this._OnTime != value))
				{
					this.OnOnTimeChanging(value);
					this.SendPropertyChanging();
					this._OnTime = value;
					this.SendPropertyChanged("OnTime");
					this.OnOnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacitance", DbType="Real")]
		public System.Nullable<float> Capacitance
		{
			get
			{
				return this._Capacitance;
			}
			set
			{
				if ((this._Capacitance != value))
				{
					this.OnCapacitanceChanging(value);
					this.SendPropertyChanging();
					this._Capacitance = value;
					this.SendPropertyChanged("Capacitance");
					this.OnCapacitanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasMinOnTime", DbType="Real")]
		public System.Nullable<float> MeasMinOnTime
		{
			get
			{
				return this._MeasMinOnTime;
			}
			set
			{
				if ((this._MeasMinOnTime != value))
				{
					this.OnMeasMinOnTimeChanging(value);
					this.SendPropertyChanging();
					this._MeasMinOnTime = value;
					this.SendPropertyChanged("MeasMinOnTime");
					this.OnMeasMinOnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasMaxOnTime", DbType="Real")]
		public System.Nullable<float> MeasMaxOnTime
		{
			get
			{
				return this._MeasMaxOnTime;
			}
			set
			{
				if ((this._MeasMaxOnTime != value))
				{
					this.OnMeasMaxOnTimeChanging(value);
					this.SendPropertyChanging();
					this._MeasMaxOnTime = value;
					this.SendPropertyChanged("MeasMaxOnTime");
					this.OnMeasMaxOnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasMinResistance", DbType="Real")]
		public System.Nullable<float> MeasMinResistance
		{
			get
			{
				return this._MeasMinResistance;
			}
			set
			{
				if ((this._MeasMinResistance != value))
				{
					this.OnMeasMinResistanceChanging(value);
					this.SendPropertyChanging();
					this._MeasMinResistance = value;
					this.SendPropertyChanged("MeasMinResistance");
					this.OnMeasMinResistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasMaxResistance", DbType="Real")]
		public System.Nullable<float> MeasMaxResistance
		{
			get
			{
				return this._MeasMaxResistance;
			}
			set
			{
				if ((this._MeasMaxResistance != value))
				{
					this.OnMeasMaxResistanceChanging(value);
					this.SendPropertyChanging();
					this._MeasMaxResistance = value;
					this.SendPropertyChanged("MeasMaxResistance");
					this.OnMeasMaxResistanceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
